#!/bin/sh
#
# Prints subject/issuer/validity/serial for the certs generated by
# gen_certs.sh -- both the ones embedded in the firmware (main/certs/) and
# the client-side ones used by stunnel/openssl s_client (host/certs/, or
# CERT_DIR if set).
#
# Requires 'openssl'.
#

CERT_DIR=${CERT_DIR:="$(dirname "$0")/certs"}
MAIN_CERTS_DIR="$(dirname "$0")/../main/certs"

show() {
    label=$1
    file=$2
    if [ ! -f "${file}" ]; then
        echo "${label}: ${file} not found"
        return
    fi
    echo "=== ${label} (${file}) ==="
    openssl x509 -in "${file}" -noout -subject -issuer -dates -serial
    echo
}

show "CA cert"           "${MAIN_CERTS_DIR}/cacert.pem"
show "ESP32 server cert" "${MAIN_CERTS_DIR}/servercert.pem"
show "Client cert"       "${CERT_DIR}/client.pem"
