#!/bin/sh
#
# Prints subject/issuer/validity/serial for the certs generated by
# gen_esp32_certs.sh / gen_client_cert.sh -- both the ones embedded in the
# firmware (main/certs/) and every client cert found in host/certs/clients/
# (or CERT_DIR/clients if set).
#
# Requires 'openssl'.
#

CERT_DIR=${CERT_DIR:="$(dirname "$0")/certs"}
MAIN_CERTS_DIR="$(dirname "$0")/../main/certs"

show() {
    label=$1
    file=$2
    if [ ! -f "${file}" ]; then
        echo "${label}: ${file} not found"
        return
    fi
    echo "=== ${label} (${file}) ==="
    openssl x509 -in "${file}" -noout -subject -issuer -dates -serial
    echo
}

show "CA cert"           "${MAIN_CERTS_DIR}/cacert.pem"
show "ESP32 server cert" "${MAIN_CERTS_DIR}/servercert.pem"

for f in "${CERT_DIR}/clients"/*.pem; do
    [ -e "$f" ] || continue
    name=$(basename "$f" .pem)
    show "Client cert (${name})" "$f"
done
